version: '2.2'
services:
  mysql:
    extends:
      file: mysql.yml
      service: mysql
  rabbitmq:
    extends:
      file: rabbitmq.yml
      service: rabbitmq
  redis:
    extends:
      file: redis.yml
      service: redis
  es01:
    extends:
      file: elasticsearch.yml
      service: es01
  es02:
    extends:
      file: elasticsearch.yml
      service: es02
  es03:
    extends:
      file: elasticsearch.yml
      service: es03
  kibana:
    extends:
      file: elasticsearch.yml
      service: kibana
  logstash:
    extends:
      file: elasticsearch.yml
      service: logstash
  kafka:
    extends:
      file: kafka.yml
      service: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
  zookeeper:
    extends:
      file: kafka.yml
      service: zookeeper
  hazelcast:
    extends:
      file: hazelcast.yml
      service: hazelcast
  hazelcast-management-center:
    extends:
      file: hazelcast.yml
      service: hazelcast-management-center