version: '2.2'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.9
    environment:
      - 'JAVA_OPTS=-Xms1024m -Xmx1024m'
      - 'discovery.type=single-node'
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.9
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es:9200
      ELASTICSEARCH_HOSTS: http://es:9200
  logstash:
    image: docker.elastic.co/logstash/logstash:6.8.9
    volumes:
      # - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      # - ./logstash/pipeline/:/usr/share/logstash/pipeline/
    environment:
      ELASTICSEARCH_HOST: es
      ELASTICSEARCH_PORT: 9200
      INPUT_TCP_PORT: 5000
      INPUT_UDP_PORT: 5000
      INPUT_HTTP_PORT: 5001
      LOGSTASH_DEBUG: false