version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.9
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms256m -Xmx256m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ~/Documents/eunex/backend/docker/es01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.9
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms256m -Xmx256m'
      - 'discovery.zen.ping.unicast.hosts=es01,es03'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ~/Documents/eunex/backend/docker/es02:/usr/share/elasticsearch/data
    ports:
      - 9201:9201
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.9
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms256m -Xmx256m'
      - 'discovery.zen.ping.unicast.hosts=es02,es03'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ~/Documents/eunex/backend/docker/es03:/usr/share/elasticsearch/data
    ports:
      - 9202:9202
  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.9
    volumes:
      - ~/Documents/eunex/backend/docker/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
  logstash:
    image: docker.elastic.co/logstash/logstash:6.8.9
    volumes:
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/
    ports: 
      - 5000:5000
      - 5001:5001/udp
      - 5044:5044
      - 9600:9600
    environment:
      ELASTICSEARCH_HOSTS: http://es01:9200
      INPUT_TCP_PORT: 5000
      INPUT_UDP_PORT: 5000
      INPUT_HTTP_PORT: 5001
      LOGSTASH_DEBUG: 'false'