version: '2.2'
services:
  hazelcast:
    image: hazelcast/hazelcast:3.12.7
    environment:
      - 'HAZELCAST_JAVA_OPTS=-Dhazelcast.local.publicAddress=localhost:5701'
    ports:
      - 5701:5701
  hazelcast-management-center:
    image: hazelcast/management-center:3.12.9
    ports:
      - 8180:8080